In [1]:
import numpy as np
import pandas as pd

In [2]:
url = 'https://bit.ly/HDSC-StageOneDataset'
df_quiz_data = pd.read_csv(url,error_bad_lines=False)

df_quiz_data.describe(include = 'all')

record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2006_12_281_1_5               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

###### QUESTION 1

In [3]:
A = [1,2,3,4,5,6] 
B = [13, 21, 34]
print(A)
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 13, 21, 34]


###### QUESTION 2

In [4]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###### QUESTION 3

In [5]:
#df_quiz_data.groupby('fuel_type_code_pudl').mean()
low_avg_fuel = df_quiz_data.groupby('fuel_type_code_pudl').mean()
low_avg_fuel['fuel_cost_per_unit_burned'].idxmin()

'gas'

###### QUESTIION 4

In [6]:
df_des = df_quiz_data.describe()
df_des.iloc[[2,-2],3].round(decimals=2)

std    10.60
75%    17.01
Name: fuel_mmbtu_per_unit, dtype: float64

###### QUESTION 5

In [7]:
print(df_quiz_data['fuel_qty_burned'].skew().round(decimals=2))
print(df_quiz_data['fuel_qty_burned'].kurtosis().round(decimals=2))


15.85
651.37


###### QUESTION 6 AND QUESTION 7

In [8]:
df_mis_tot = df_quiz_data.isnull().sum()
df_miss_feat= df_mis_tot.loc[df_quiz_data.isnull().sum() > 0].to_frame()
val = df_miss_feat.index
#print(df_miss_feat,'\n\n')
#print(val,'\n\n')
df_mis_val = df_miss_feat.iat[0,0]
df_tot_cnt = df_quiz_data['fuel_unit'].count()
#print(df_mis_val)
miss_perc = ((df_mis_val/df_tot_cnt) * 100).round(decimals=3)
#print(miss_perc)
print("Feature: {},Total: {}, Percent: {}".format(val,df_mis_val,miss_perc))


print('\n\n', "Categorical and Mode Imputation")

Feature: Index(['fuel_unit'], dtype='object'),Total: 180, Percent: 0.613


 Categorical and Mode Imputation


###### QUESTION 8

In [9]:
df_quiz_data.corr()

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

In [10]:
df_corr_data = df_quiz_data.corr()
df_corr_sortd = df_corr_data.loc['fuel_cost_per_unit_burned'].abs().sort_values()
#print(df_corr_sortd)
#Since my result is sorted by descending. I can get my second and third lowest by indexing
df_corr_sortd.iloc[1:3].index

Index(['fuel_mmbtu_per_unit', 'fuel_cost_per_unit_delivered'], dtype='object')

###### QUESTION 9

In [11]:
df_coal = (df_quiz_data[df_quiz_data["fuel_type_code_pudl"] == 'coal']).groupby('report_year').sum()
print(df_coal['fuel_cost_per_unit_burned'])
df_coal_grp= df_coal['fuel_cost_per_unit_burned']

report_year
1994     14984.572
1995     14571.785
1996     12694.803
1997     43742.178
1998     11902.597
1999     16303.468
2000    100428.831
2001     15109.012
2002      9171.164
2003     30954.110
2004      9632.063
2005     11107.182
2006     12402.684
2007     12965.171
2008     14331.348
2009     45554.858
2010     88627.745
2011     17001.015
2012     17546.097
2013     17629.860
2014     15412.197
2015     13338.235
2016     11100.925
2017     10254.284
2018      9488.197
Name: fuel_cost_per_unit_burned, dtype: float64


In [12]:
df_coal_grp.at[1994]
df_coal_grp.at[1998]
df_coal_chng = ((df_coal_grp.at[1998] - df_coal_grp.at[1994])/df_coal_grp.at[1994]) *100
print(df_coal_chng.round(decimals=0))

-21.0


###### QUESTION 10

In [13]:
df_avg_fuel = df_quiz_data.groupby('report_year').mean()
df_avg_fuel['fuel_cost_per_unit_delivered'].idxmax()

1997